// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojrekbttkriwwyaupbox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qcmVrYnR0a3Jpd3d5YXVwYm94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODczMzQsImV4cCI6MjA2MTk2MzMzNH0.no8Tk71APiFYmu5ySR06h-caNW0WOolVG3fmo5YKuIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);